server:
  port: 8090

spring:
  application:
    name: zipkinclient
  sleuth:
    web:
      enabled: true #启动监控
    sampler:
      probability: 1.0 #设置采样比例
  zipkin:
    base-url: http://localhost:9090/ # zipkin服务端地址

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/