server:
  port: 8763

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/2020GetGoodOffer/test.git
          search-paths: config
          username: 2020GetGoodOffer
          password: sjh2019.
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
